[tool.ruff]
line-length = 90
target-version = "py311"

[tool.ruff.lint]
select = ["ALL"]
ignore = [
  "D", # flake8-docstrings
  "FIX", # flake8-fixme
  "TD", # flake8-todo
  "E501", # Never enforce line length
  "RET504", # Unnecessary variable assignment before `return` statement
  "RUF001", # ruff unicode specific rules
  "RUF002", # ruff unicode specific rules
  "RUF003", # ruff unicode specific rules
  "COM812", # Missing trailing comma conflicts with ruff format
  "ISC001", # single-line-implicit-string-concatenation conflicts with ruff format
  "FBT001", # Boolean-typed positional argument in function definition
  "FBT002", # Boolean default positional argument in function definition
]
unfixable = [
  "B", # Avoid trying to fix flake8-bugbear violations.
  "ERA", # Avoid deleting commented-out code
]

[tool.ruff.lint.per-file-ignores]
"tests*/*" = [
  "INP001", # Add an `__init__.py`.
  "PLR2004", # Magic value used in comparison
  "S101", # Use of assert detected
]
[tool.ruff.lint.isort]
lines-after-imports = 2

[tool.ruff.format]
docstring-code-format = true
